repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'
    hooks:
      - id: autopep8
        args: [--in-place]
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
